### PR TITLE
proposed text in section 3.65. If agreed, will apply to the other sec…

### PR DESCRIPTION
**Pull request by JohnMoehrke**
…tions.

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@lynnfel do you like this wording pattern? If looking at it is not clear, I can help.

**Comment by lynnfel** [comment]
I cannot find the comment where I complained about the original wording.    I'm not sure that what you proposed is an improvement.

How about splitting it into two sentences, "An MHD Document Source, when grouped with an IUA Authorization Client, shall use [ITI-71] Get Access Token to request the following scope from the IUA Authorization Server.  This enables the MHD Document Source to submit a document using the Provide Document Bundle [ITI-65] transaction with the authorizing token (in Incorporate Authorization Token [ITI-72]).

...not sure whether this is an improvement, or not...

**Comment by JohnMoehrke** [comment]
Your original suggestion is in Issue #67 

But I do like your latest improvements. Two sentences are better than one. I will replicate this on all the transactions. It will receive further review at the virtual face-to-face.

**Comment by JohnMoehrke** [comment]
closes #48

**Pull request merged**
